---
title: "Homework 12 -- Time Series"
author: "Richard Hart"
date: "April 5, 2019"
output: 
  html_document:
    keep_md: true
---

# Homework Assignment 12 -- Time Series

Loading Libraries
```{r, echo=TRUE, warning=FALSE}
library("dygraphs")
library("forecast")
library("fpp2")
```

### Warm Up: Brief Financial Data, European Stock Market DataSets

a. European Stock Market Data Information
```{r, eval=FALSE, echo=TRUE}
help("EuStockMarkets")
```

```{r, echo=TRUE}
str(EuStockMarkets)
```

Create dataset from the DAX Index
```{r, echo=TRUE}
Eu_DAX <- EuStockMarkets[, "DAX"]
```

b. Plot of European Stock Market Data with an Indication at 1997
```{r, echo=TRUE}
plot(Eu_DAX, col="blue", main="Daily Closing Prices of the European Stock Index, DAX (1991-1998)", ylab="European Stock Market Index DAX", xlab="Year")
abline(v=1997, col="red")
```

c. Decomposition of DAX Index Time Series into its components (multiplicative model)
```{r, echo=TRUE}
EuDaxComp <- decompose(Eu_DAX, type = "multiplicative")
plot(EuDaxComp, col="blue", ylab="Component", xlab="Year" )
abline(v=1997, col="red")
```
